language: dart

dart:
  - stable

addons:
  chrome: stable
  
dart_task: 
  - dartfmt 

install: 
  - git clone https://github.com/flutter/flutter.git -b stable 

before_script:
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter packages get
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter analyze
  - ./flutter/bin/flutter build web
  
cache:
  directories:
    - $HOME/.pub-cache
