language: dart

flutter:
  - stable

addons:
  chrome: stable
  
before_script:
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter build web
  
cache:
  directories:
    - $HOME/.pub-cache
